export const GET_EARRINGS_REQ = "GET_EARRINGS_REQ"
export const GET_EARRINGS_SUC = "GET_EARRINGS_SUC"
export const GET_EARRINGS_FAIL = "GET_EARRINGS_FAIL"

export const GET_RINGS_REQ = "GET_RINGS_REQ"
export const GET_RINGS_SUC = "GET_RINGS_SUC"
export const GET_RINGS_FAIL = "GET_RINGS_FAIL"

export const GET_NECKPIECE_REQ = "GET_NECKPIECE_REQ"
export const GET_NECKPIECE_SUC = "GET_NECKPIECE_SUC"
export const GET_NECKPIECE_FAIL = "GET_NECKPIECE_FAIL"

export const GET_BRACELETS_REQ = "GET_BRACELETS_REQ"
export const GET_BRACELETS_SUC = "GET_BRACELETS_SUC"
export const GET_BRACELETS_FAIL = "GET_BRACELETS_FAIL"

export const GET_INDIVIDUAL_REQ = "GET_INDIVIDUAL_REQ"
export const GET_INDIVIDUAL_SUC = "GET_INDIVIDUAL_SUC"
export const GET_INDIVIDUAL_FAIL = "GET_INDIVIDUAL_FAIL"